### ISSUE TITLE
mobile: Previous button not shown in portrait mode

### ISSUE THREAD

**Issue by sorenbs** [learnrelay/learnrelay#10]
Previous button not shown in portrait mode

![img_0175](https://cloud.githubusercontent.com/assets/281337/18140799/638be738-6fb7-11e6-8c7a-5add514598a5.PNG)

**Comment by julianbauer** [comment]
That's intended, because there's not enough space for both the next and previous button, so we thought it would make sense to focus on the main user journey. What do you think? :)
