### ISSUE TITLE
mobile: Funky stuff when you scroll to the bottom of Step1: Warmup

### ISSUE THREAD

**Issue by sorenbs** [learnrelay/learnrelay#12]
![ezgif-1740446341](https://cloud.githubusercontent.com/assets/281337/18141048/4979c2a6-6fb8-11e6-8d89-b43ef2624b5a.gif)

**Comment by marktani** [comment]
is this still an issue?

**Comment by schickling** [comment]
@julianbauer ?

**Comment by julianbauer** [comment]
on my phone looks alright
