### ISSUE TITLE
User Experience Intro Page

### ISSUE THREAD

**Issue by aarmand** [learnrelay/learnrelay#23]
The video on the the intro page, https://learnrelay.org/overview/intro, references the graphql endpoint but there is no orange button at the bottom of the right side panel as is represented in the video. The button does not become available until you go through the "Getting Started" section here: https://learnrelay.org/introduction/get-started. From a mindset point of view, I would be starting to doubt myself here thinking that I have something set up wrong or I wont be able to do this on my machine. I would suggest communicating above the video or in the video with a slide or overlay that the graphql endpoint is not available on this page yet.

**Comment by schickling** [comment]
Very good point! @JulianTapales what do you think?

**Comment by ram535ii** [comment]
So true

**Comment by JulianTapales** [comment]
Very valid point and great timing, I am just redoing that video now in light of @marktani 's content additions and have just recorded and added the missing part you pointed out! The new video should be live in the next few days. Thanks a lot for the feedback :-)
