### ISSUE TITLE
screen scroll cutting off content on "getting started" page

### ISSUE THREAD

**Issue by aarmand** [learnrelay/learnrelay#25]
I'm on page https://learnrelay.org/introduction/get-started. I'm on a desktop monitor on a Windows 10 OS. I have the screen split with Atom IDE on left and Firefox on right. At this width on the 'get started' page, you lose some of the content which is not fitting on the screen. A solution would be getting the media queries adjusted or making the left panel collapsible on this view width with a media query. Screenshot attached.
![learnrelay1](https://cloud.githubusercontent.com/assets/2370391/18682238/b92c99da-7f6b-11e6-8acc-6200bfa2856b.PNG)

**Comment by julianbauer** [comment]
Content isn't cut off anymore
