### ISSUE TITLE
Git Checkout Sign Posting for Step-01 , 02 etc

### ISSUE THREAD

**Issue by aarmand** [learnrelay/learnrelay#28]
Git checkouts for every stage of a course/tutorial is an amazing idea. Allows for diffiing, if you know how to do that, and generally keeping up. I have done countless tutorials and I have always appreciated branches per section. I have also coded right past them, beginning to end. I recommend that you clearly mark where a git checkout should happen so people can benefit from them.

**Comment by marktani** [comment]
Did you see [this section](https://learnrelay.org/introduction/get-started#making-the-most-of-this-tutorial) in the introduction chapter?

I agree that we should remind the readers at the start of every section to checkout the correct branch.

As for the branch workflow itself, do you have suggestions for it?

**Comment by schickling** [comment]
I think pasting the `git checkout` command into the first few exercises should be a good idea indeed!

**Comment by aarmand** [comment]
@marktani i saw the section. My point was that I read that section in every tutorial then forget about it. Might be just me. I usually end up following along until i have a problem. By then I am at get checkout 67 or something. I suppose it doesnt matter because you can git checkout what the solution you have a problem with. But then if the problem was something lingering from back in the code, then you kind made a mess of it. Just throwing my experience at you for what its worth.
