### ISSUE TITLE
React Router Relay - unclear how ViewerQueries ties in

### ISSUE THREAD

**Issue by ram535ii** [learnrelay/learnrelay#30]
For all the `<Route>`s you do `queries={ViewerQueries}` where in all the previous sections we have been building on top of this query object. So what happened to all that work we did? 

I know the answer is fundamentally in the code, but as I read the section I just couldn't like the ideas.

**Comment by marktani** [comment]
I don't understand the issue you are describing here, can you clearify?

**Comment by ram535ii** [comment]
Sorry for being so unclear, must have been tired. So I'm talking about [this](https://learnrelay.org/routes/react-router-relay/) section of the tutorial. 

It's basically unclear why we are passing in the `ViewerQueries` object into the routes. The user has just spent the last few sections reading about building queries on top of `viewer` and it would just be nice to have some more explanation connecting the two. For example (and I'm making this up, probably wrong), 'The ViewerQueries object is passed into every route so that the component for that route can attach its query requirements to the top level query`. 

Is that a little clearer?

**Comment by marktani** [comment]
Ok I see. Thanks for the clarification! It's a good idea to come back to the `ViewerQueries` as it's something familiar to the user.

**Comment by marktani** [comment]
Basically I'm thinking of repeating and extending on information given here: https://learnrelay.org/queries/containers-fragments#exercise-02-prepare-the-listpage-for-further-action

**Comment by ram535ii** [comment]
Yea, I think that makes sense. It’s just establishing that link between
passing the viewer object in and how/why it gets used by “sub-queries”

**Comment by marktani** [comment]
I added a sentence on the `ViewerQueries`, I hope it is clear now.
