### ISSUE TITLE
Logging In/Cacheing.

### ISSUE THREAD

**Issue by aarmand** [learnrelay/learnrelay#31]
I just came back to this after a few days. I thought, "where was I?". Then I opened the repo I was working in. Maybe People can log in and save there progress. Reopen at the point they were at. Just a UX tweak.

(Im just throwing everything at you as it comes as requested. For you to decide, obviously.)

**Comment by schickling** [comment]
Oh so the progress wasn't saved for you? Did you use another browser when coming back?

**Comment by aarmand** [comment]
Indeed. Just checked Firefox. Guess that is where I was working.

**Comment by schickling** [comment]
I see. I guess it's "good enough" for now to not sync the progress across browsers as this introduces a lot of additional complexity.
