### ISSUE TITLE
Adding Api URL for GraphQL Server

### ISSUE THREAD

**Issue by aarmand** [learnrelay/learnrelay#34]
Is it expected to that we enter the endpoint url after each checkout?

**Comment by marktani** [comment]
Yes, this is intended as explained [here](https://learnrelay.org/introduction/get-started#making-the-most-of-this-tutorial).

We understand that this is cumbersome, but we think that introducing another system that tries to simplify this step introduces too much complexity by itself. The current situation is cumbersome but easy to understand.
