### ISSUE TITLE
Safari: The GraphQL Server sticky pop out

### ISSUE THREAD

**Issue by samerbuna** [learnrelay/learnrelay#41]
On Safari, the X to hide the GraphQL server pop out is not reachable. (Maybe depending on the screen size)

**Comment by schickling** [comment]
Can you provide a screenshot?

**Comment by samerbuna** [comment]
<img width="1920" alt="screen shot 2016-10-11 at 1 40 54 pm" src="https://cloud.githubusercontent.com/assets/75209/19287893/83aaa704-8fb8-11e6-8098-aaf2bf9f48b6.png">

**Comment by schickling** [comment]
@julianbauer any update on this?

**Comment by julianbauer** [comment]
There was a small positioning issue, it's fixed on master and will be implemented with the next deploy. Thanks for reporting!
