### ISSUE TITLE
Disconnect in instructions

### ISSUE THREAD

**Issue by samerbuna** [learnrelay/learnrelay#42]
There is no continuous path in the instructions. There is a disconnect between end of step-2 and start of step-3 for example, a user can't just follow the instructions, they have to checkout branches for every step. It was a bit confusing.

Maybe a hint to checkout branch X at the beginning of every step?

**Comment by schickling** [comment]
Yeah, that makes a lot of sense! @marktani any ideas on how to embed this?

**Comment by marktani** [comment]
Thanks for pointing this out! I added a notice to all the exercises in fdd1553b7241971c4f0c57ae285e6875f53c5a97.
