### ISSUE TITLE
Mobile: NEXT-Buttons should be displayed at anytime at the bottom of each page.

### ISSUE THREAD

**Issue by julianbauer** [learnrelay/learnrelay#47]
Currently only appear after you scrolled below the end of the page

**Comment by schickling** [comment]
Thanks for brining that up.
What's needed in order to accomplish that what you cannot do yourself, @julianbauer?

**Comment by julianbauer** [comment]
Best would be to disable the jumpActive toggle below 900px, and leave it active always. I found a css only version that overrides it though.

**Comment by schickling** [comment]
Alright, perfect. So this is solved and can be closed @julianbauer?
