### ISSUE TITLE
Can we see the GraphQL schema used for the tutorial?

### ISSUE THREAD

**Issue by naomik** [learnrelay/learnrelay#57]
After completing the https://www.learnrelay.org/ tutorial, I found myself wishing I could see the schema.js file that's used on the server side.

Any chance that's published anywhere we can look at it?

**Comment by iamglenbacs** [comment]
This would really be helpful

**Comment by marktani** [comment]
Hey, the GraphQL server is setup using [Graphcool](https://graph.cool) so there's no `schema.js` file. But you can download the schema in IDL syntax using a tool like [get-graphql-schema](https://github.com/graphcool/get-graphql-schema)

> get-graphql-schema ENDPOINT_URL > schema.json
