### ISSUE TITLE
Starting tutorial with graphql backend is not working properly

### ISSUE THREAD

**Issue by zirho** [learnrelay/learnrelay#58]
https://www.learnrelay.org/introduction/get-started/?code=6efc69abf6859a820f9d#graphql-endpoint

Once I authenticate my github account and redirect to the page, I got this error.

![image](https://cloud.githubusercontent.com/assets/1251296/24068195/db9a1a9a-0b45-11e7-95e8-7d1952febb12.png)

**Comment by schickling** [comment]
Hi @zirho! Can you ping me in [Slack](https://slack.graph.cool)? I'll try to fix it with you asap!

**Comment by schickling** [comment]
Is this still an issue @zirho?

**Comment by g-combs** [comment]
As a follow-up, I'm seeing issues at this point also with similar behavior.

**Comment by marktani** [comment]
Hey @zirho and @g-combs, could you try to:
- remove the Learn Relay authorization from your GitHub account
- logout of GitHub
- try again?

**Comment by michalczaplinski** [comment]
I've encountered the same issue:

![graphcool](https://user-images.githubusercontent.com/5417266/27809580-37f02400-6051-11e7-8540-3ef75d2f557e.jpeg)

It looks like the issue are the CORS headers.

**Comment by marktani** [comment]
Hey @michalczaplinski can you try again as I pointed out above?

**Comment by michalczaplinski** [comment]
hey @marktani - I have just tried without logging out of github first and I cannot reproduce the problem anymore.

**Comment by marktani** [comment]
Awesome! I'll close this issue, if anyone else hits any issue please contact me or create another issue 🙂
