### ISSUE TITLE
Get GraphQL Endpoint doesn't work

### ISSUE THREAD

**Issue by martinTapdaq** [learnrelay/learnrelay#71]
Guys, after click on that Get GraphQL Endpoint button and sign in with github nothing happens. I tried it twice and I was waiting at least 10min without any change except it shows that in-progress circle..

**Comment by azat-co** [comment]
Not working for me either!

![screenshot 2018-01-27 09 38 00](https://user-images.githubusercontent.com/1137314/35474631-f2a03974-0345-11e8-87f3-926285c6ad6a.png)

**Comment by marktani** [comment]
The learn relay tutorial has been deprecated :) Please check https://www.howtographql.com/ instead.
